### PR TITLE
amrinder1189/ issue fixed #111 Wrong border color for github icon 

### LINKED ISSUE #111: Wrong border color for github icon
**Describe the bug**
The border color for github icon on desktop and mobile is grey.

**To Reproduce**

1. Go to Homepage
2. Look at the nav bar and locate the github icon if you are on desktop, on mobile, open
the navigation bar and see the github icon border.

**Expected behavior**
The border color should be the primary color

**Screenshots**
Screen Shot 2023-05-13 at 07 06 11

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by amrinder1189**
I have changed the border color to primary and done the necessary checks as well, Now in both views Desktop as well as Mobile the border around the GitHub is primary.

As this is my first contribution I am very happy to contribute and Let me know in case of any query

### CODE REVIEW

File: components/ui/organisms/Header.tsx [hunk 1]
```diff
@@ -114,7 +114,10 @@ export default function Header() {
                   </Link>
                 </li>
                 <li className="w-[100%]">
-                  <div className="w-[100%] mt-[1rem] text-center border-[1px] p-2 rounded-md border-primary font-normal">
+                  <div
+                    className="w-[100%] mt-[1rem] text-center border-[1px] p-2 rounded-md border-primary font-normal"
+                    style={{ border: '1px solid #0275d8' }}
```
Comment (CeoFred) [inline components/ui/organisms/Header.tsx:119]: #00522A is the correct color, apply same change below.

**Review by CeoFred — CHANGES_REQUESTED** [review]

**Comment by CeoFred** [comment]
This fixes #111

File: components/ui/organisms/Header.tsx (hunk 1 above)
Comment (amrinder1189) [reply components/ui/organisms/Header.tsx:119]: sure @CeoFred

**Review by CeoFred — APPROVED** [review]
